In [2]:
import pandas as pd
df1=pd.read_csv("/content/departments.csv")
df1

   Department_ID Department_Name       Location
0              1              IT       New York
1              2              HR  San Francisco
2              3         Finance        Chicago
3              4       Marketing    Los Angeles
4              5      Operations        Seattle

In [33]:
df2=pd.read_csv("/content/employees.csv")
df2

   Employee_ID          Name  Department_ID  Salary
0          101   Alice Brown            1.0   60000
1          102     Bob Smith            2.0   45000
2          103   Charlie Doe            1.0   75000
3          104   Daisy Evans            3.0   50000
4          105    Eva Taylor            4.0   80000
5          106  Frank Wilson            NaN   40000

In [11]:
#Inner Join: Perform an inner join between the employees and departments datasets
#to get information about employees along with their department names and locations.
inner=pd.merge(df2,df1,on="Department_ID",how="inner")
inner

,Employee_ID,Name,Department_ID,Salary,Department_Name,Location
0,101,Alice Brown,1.0,60000,IT,New York
1,102,Bob Smith,2.0,45000,HR,San Francisco
2,103,Charlie Doe,1.0,75000,IT,New York
3,104,Daisy Evans,3.0,50000,Finance,Chicago
4,105,Eva Taylor,4.0,80000,Marketing,Los Angeles

In [12]:
#Left Join: Perform a left join between the employees and departments datasets.
left=pd.merge(df2,df1,on="Department_ID",how="left")
left

,Employee_ID,Name,Department_ID,Salary,Department_Name,Location
0,101,Alice Brown,1.0,60000,IT,New York
1,102,Bob Smith,2.0,45000,HR,San Francisco
2,103,Charlie Doe,1.0,75000,IT,New York
3,104,Daisy Evans,3.0,50000,Finance,Chicago
4,105,Eva Taylor,4.0,80000,Marketing,Los Angeles
5,106,Frank Wilson,NaN,40000,NaN,NaN

In [13]:
#Right Join: Perform a right join between the departments and employees datasets.
#Why might this join be useful in certain scenarios?
right=pd.merge(df1,df2,on="Department_ID",how="right")
right

,Department_ID,Department_Name,Location,Employee_ID,Name,Salary
0,1.0,IT,New York,101,Alice Brown,60000
1,2.0,HR,San Francisco,102,Bob Smith,45000
2,1.0,IT,New York,103,Charlie Doe,75000
3,3.0,Finance,Chicago,104,Daisy Evans,50000
4,4.0,Marketing,Los Angeles,105,Eva Taylor,80000
5,NaN,NaN,NaN,106,Frank Wilson,40000

In [14]:
#Full Outer Join: Perform a full outer join between the employees and departments datasets.
outer=pd.merge(df2,df1,on="Department_ID",how="outer")
outer

,Employee_ID,Name,Department_ID,Salary,Department_Name,Location
0,101.0,Alice Brown,1.0,60000.0,IT,New York
1,103.0,Charlie Doe,1.0,75000.0,IT,New York
2,102.0,Bob Smith,2.0,45000.0,HR,San Francisco
3,104.0,Daisy Evans,3.0,50000.0,Finance,Chicago
4,105.0,Eva Taylor,4.0,80000.0,Marketing,Los Angeles
5,NaN,NaN,5.0,NaN,Operations,Seattle
6,106.0,Frank Wilson,NaN,40000.0,NaN,NaN

In [15]:
# Group Employees by Department:
# Group the employees dataset by Department_ID and calculate:
# Total salary in each department.
total_salary=df2.groupby("Department_ID")["Salary"].sum()
total_salary

Department_ID
1.0    135000
2.0     45000
3.0     50000
4.0     80000
Name: Salary, dtype: int64

In [16]:
# Average salary in each department.
avg_salary=df2.groupby("Department_ID")["Salary"].mean()
avg_salary

Department_ID
1.0    67500.0
2.0    45000.0
3.0    50000.0
4.0    80000.0
Name: Salary, dtype: float64

In [20]:
#Join the datasets and group by Location to find:
# The number of employees in each location.
outer=pd.merge(df2,df1,on="Department_ID",how="outer")
a=outer.groupby("Location")["Employee_ID"].count()
a

Location
Chicago          1
Los Angeles      1
New York         2
San Francisco    1
Seattle          0
Name: Employee_ID, dtype: int64

In [21]:
# Total salary of employees in each location.
b=outer.groupby("Location")["Salary"].sum()
b

Location
Chicago           50000.0
Los Angeles       80000.0
New York         135000.0
San Francisco     45000.0
Seattle               0.0
Name: Salary, dtype: float64

In [44]:
#Filter employees with a salary above $50,000 and group them by
#Department_ID. Calculate the average salary for these employees in each department
filter=df2["Salary"]>50000
b=df2[filter]
c=b.groupby("Department_ID")["Salary"].mean()
c

Department_ID
1.0    67500.0
4.0    80000.0
Name: Salary, dtype: float64